spring:
  application:
    name: Spring_Mini_Project
  datasource:
    url: jdbc:postgresql://localhost:5432/article_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false